---
- hosts: minecraft_server
  name: Setup minecraft_server
  become: yes

  roles:
    - base_setup
    - role: node_exporter
      tags: [ "node_exporter" ]

  tasks:
    - name: Create minecraft user
      user:
        name: minecraft
        create_home: yes

    - name: Install OpenJDK
      apt:
        name: openjdk-21-jre-headless
        state: present

    - name: Fetch minecraft server jar file
      get_url:
        url: https://piston-data.mojang.com/v1/objects/450698d1863ab5180c25d7c804ef0fe6369dd1ba/server.jar
        dest: /tmp

    - name: Copy jar file to minecraft user home
      copy:
        src: /tmp/server.jar
        remote_src: yes
        dest: /home/minecraft/server.jar
        mode: 0644
        owner: minecraft
        group: minecraft

    - name: Create eula file
      copy:
        content: |
          eula=true
        dest: /home/minecraft/eula.txt
        mode: 0644
        owner: minecraft
        group: minecraft

    - name: Create minecraft systemd service
      template:
        src: minecraft.service.j2
        dest: /etc/systemd/system/minecraft.service
        mode: 0644

    - name: Start and enable minecraft systemd service
      systemd:
        daemon_reload: yes
        name: minecraft
        state: restarted
        enabled: yes




